name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run test Jobs
    runs-on: ubuntu-20.04
    env:
      influxdb_version: latest
      influxdb_org: influxdata
      influxdb_user: ci_user
      influxdb_password: password
      influxdb_bucket: dummy      
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Checkout InfluxDB installer
      uses: actions/checkout@v3
      with:
        repository: davidhemp/influxdb-action 
        path: './influxdb'
    - name: Download influxdb
      run: ./influxdb/install-influxdb.sh
    - name: Configure influxdb
      run: ./influxdb/setup-influxdb.sh
    - name: Run influx-tests
      run: ./run


    - run: sudo useradd -r -c "PBS data service management account" pbsdata
    - run: wget https://vcdn.altair.com/rl/OpenPBS/openpbs_23.06.06.ubuntu_20.04.zip
    - run: sudo apt-get install unzip libhwloc15 libical3 libpq5 munge
    - run: unzip openpbs_23.06.06.ubuntu_20.04.zip
    - run: sudo dpkg -i openpbs_23.06.06.ubuntu_20.04/openpbs-server_23.06.06-1_amd64.deb
    - run: sudo create-munge-key
    - run: sudo ln -s /lib64/libmunge.so.2 /lib64/libmunge.so
    - run: sudo sed -i 's/PBS_START_MOM=0/PBS_START_MOM=1/g' /etc/pbs.conf
    - run: sudo systemctl restart pbs
    - run: mkdir -p tests/logs

    - run: sudo iptables -F

    - run: sudo /opt/pbs/bin/qmgr < tests/test-cluster
    - run: sudo /opt/pbs/bin/pbsnodes -a > tests/logs/pbsnodes.log
    - run: for j in $(ls tests/jobs/); do /opt/pbs/bin/qsub tests/jobs/${j}; done
    - run: /opt/pbs/bin/qstat > tests/logs/qstat-start.log
    - run: sleep 5
    - run: tests/check-jobs.sh > tests/logs/check-jobs.log

    - name: artifact logs for download
      uses: actions/upload-artifact@v3
      with:
        name: output-logs
        path: tests/logs
