name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run test Jobs
    runs-on: ubuntu-20.04
    env:
      INFLUXDB_ORG: influxdata
      INFLUXDB_USER: ci_user
      INFLUXDB_PASSWORD: password
      INFLUXDB_BUCKET: dummy      
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v3
    - run: sudo iptables -F

    - name: Install influxdb
      run: tests/influxdb/install.sh
    - name: Start influxdb
      run: /usr/local/bin/influxdb --http-bind-address :8086 
    - name: Test influxdb
      run: tests/influxdb/test.sh

    - name: Install monitoring env
      run: bash install.sh 
    - name: Test monitoring
      run: bash run.sh

    - name: Install PBS
      run: tests/pbs/install.sh

    - name: PBS tests
      run: |
        mkdir -p tests/logs
        sudo /opt/pbs/bin/qmgr < tests/test-cluster
        sudo /opt/pbs/bin/pbsnodes -a > tests/logs/pbsnodes.log
        for j in $(ls tests/jobs/); do /opt/pbs/bin/qsub tests/jobs/${j}; done
        /opt/pbs/bin/qstat > tests/logs/qstat-start.log
        sleep 5
    - name: Check PBSPro test jobs
      run: tests/check-jobs.sh > tests/logs/check-jobs.log

    - name: artifact logs for download
      uses: actions/upload-artifact@v3
      with:
        name: output-logs
        path: tests/logs
