name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run test Jobs
    runs-on: ubuntu-20.04
    env:
      INFLUXDB_START: true
      INFLUXDB_URL: http://localhost:8086 
      INFLUXDB_ORG: influxdata
      INFLUXDB_USER: ci_user
      INFLUXDB_PASSWORD: password
      INFLUXDB_BUCKET: dummy      
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v3
    - run: sudo iptables -F

    - name: Install influxdb
      run: tests/influxdb/install.sh
    - name: Test influxdb
      run: tests/influxdb/test.sh
    - name: Grab Token and update env
      run: echo "INFLUXDB_TOKEN=$(influx auth list | grep $INFLUXDB_USER | grep -o '[[:alnum:]\_\-]*==')" >> $GITHUB_ENV

    - name: Install monitoring env
      run: bash install.sh 
    - name: Test monitoring
      run: bash run.sh

    - name: Install PBS
      run: tests/pbs/install.sh

    - name: Run PBS tests
      run: tests/pbs/run-tests.sh
    - name: Check PBSPro test jobs
      run: tests/check-tests.sh > tests/logs/check-tests.log

    - name: artifact logs for download
      uses: actions/upload-artifact@v3
      with:
        name: output-logs
        path: tests/logs
