name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run test Jobs
    runs-on: ubuntu-20.04
    steps: 
    #Checkout repo so job can acces it
    - uses: actions/checkout@v3

    - name: Install InfluxDB
      uses: davidhemp/influxdb-action@v2
      with:
        influxdb_version: latest
        influxdb_org: influxdata
        influxdb_user: ci_user
        influxdb_password: password
        influxdb_bucket: dummy      
